language: node_js
node_js:
  - 14

# cache node_modules directories
cache:
  directories:
    - client/node_modules
    - display/node_modules
    - $HOME/.cargo

before_script:
  # install rustup if not cached
  - test -f $HOME/.cargo/env || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
  - source "$HOME/.cargo/env"
  # install wasm-pack
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  # build web assembly component
  - cd wasm && wasm-pack build --target web
  - ls -la
  # install node modules
  - cd ../display && npm ci
  - cd ../client && npm ci
  - cd $TRAVIS_BUILD_DIR

script:
  # run prettier to validate
  - cd client && npm run prettier:check-all
  - cd ../display && npm run prettier:check-all
  # lint the code
  - cd ../client && npm run lint
  # build the display component
  - cd ../display && npm run build
  # build the app
  - cd ../client && npm run build
